### ISSUE TITLE
failed to run custom build command for `curl-sys v0.4.20`

### ISSUE THREAD

**Issue by IThawk** [ChrisGreenaway/cargo-local-registry#154]
error: failed to run custom build command for `curl-sys v0.4.20`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install6FJvCe/release/build/curl-sys-292f2f67c3e98659/build-script-build` (exit code: 1)
--- stdout
Couldn't find libcurl from pkgconfig (Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"libcurl\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package libcurl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libcurl.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libcurl\' found\n" } }), compiling it from source...
cargo:root=/tmp/cargo-install6FJvCe/release/build/curl-sys-f175fbd292a2c0e0/out
cargo:include=/tmp/cargo-install6FJvCe/release/build/curl-sys-f175fbd292a2c0e0/out/include
cargo:static=1
cargo:rustc-cfg=link_libnghttp2
cargo:rustc-cfg=link_libz

**Comment by ChrisGreenaway** [comment]
What platform are you building on? Do you have libcurl installed?

**Comment by IThawk** [comment]
I have installed

**Comment by ChrisGreenaway** [comment]
@IThawk - so you didn't have it installed and now you do and everything is OK?

**Comment by IThawk** [comment]
still exist!

**Comment by ChrisGreenaway** [comment]
Have a look here: https://github.com/alexcrichton/curl-rust/issues/91

Looks like: `sudo apt-get install libcurl4-gnutls-dev` should sort it out for you.

**Comment by ChrisGreenaway** [comment]
@IThawk - did that fix it for you?

**Comment by IThawk** [comment]
how to solve in centos

**Comment by ChrisGreenaway** [comment]
@IThawk - it sounds like you want to know the equivalent of `sudo apt-get install` for CentOS. Is that right? If so, I think it's something like `sudo yum install`

**Comment by ChrisGreenaway** [comment]
@IThawk - did that solve the issue for you?

**Comment by ChrisGreenaway** [comment]
Closing because there's no further feedback from @IThawk and the issue is likely resolved.
