### ISSUE TITLE
Perform `cargo package`

### ISSUE THREAD

**Issue by metaclips** [ChrisGreenaway/cargo-local-registry#165]
Hello @alexcrichton @ChrisGreenaway I am trying to use this project to `cargo package` workspace crates, some crates are interdependent and require it to be published to a registry. Can I locally publish crates with cargo-local-registry.

**Comment by ChrisGreenaway** [comment]
That's not the intended use case. Instead cargo-local-registry is aimed at making a local copy of another registry.
