### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [ChrisGreenaway/cargo-local-registry#6]
This is blocked on https://github.com/rust-lang/cargo/issues/3944.

**Comment by ChrisGreenaway** [comment]
@dtolnay - I don't see a direct dependency on rustc-serialize in the Cargo.toml. The project appears to use serde. So are you happy with this issue being closed?

**Comment by dtolnay** [comment]
Looks good, this was fixed in https://github.com/ChrisGreenaway/cargo-local-registry/commit/465ac8911ad11d9210b6ba70dff2540dd48d2000. Thanks!
